services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - erp

  erp:
    image: patjawat/erp:latest
    container_name: erp
    restart: always
    volumes:
      - ./erp:/var/www/html
    networks:
      - web-network

  mysqlDB:
    image: mysql:8.0
    container_name: mysqlDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: erp
      MYSQL_PASSWORD: erp123
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - web-network

  phpmyadmin_pma:
    image: phpmyadmin
    container_name: phpmyadmin_pma
    restart: always
    environment:
      PMA_HOST: mysqlDB
    ports:
      - "8000:80"
    depends_on:
      - mysqlDB
    networks:
      - web-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    command: >
      sh -c "
      certbot certonly --webroot -w /var/www/certbot
      --email admin@example.com --agree-tos --no-eff-email
      -d rama.hospital-erp.org
      "
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx

networks:
  web-network:
    driver: bridge
