services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - erp

  erp:
    image: patjawat/erp:latest
    container_name: erp
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - mysqlDB

  mysqlDB:
    image: mysql:8.0
    container_name: mysqlDB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: erp
    volumes:
      - ./mysql/data:/var/lib/mysql

  phpmyadmin_pma:
    image: phpmyadmin
    container_name: phpmyadmin_pma
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysqlDB
      PMA_USER: root
      PMA_PASSWORD: yourpassword

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: /bin/sh
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

networks:
  default:
  web-network:
