services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - erp
    networks:
      - web-network

  erp:
    image: patjawat/erp:latest
    container_name: erp
    restart: always
    networks:
      - web-network

  mysqlDB:
    image: mysql:8.0
    container_name: mysqlDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
      MYSQL_USER: erpuser
      MYSQL_PASSWORD: erppass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - web-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_pma
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysqlDB
    networks:
      - web-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "echo 'Certbot container ready'"

volumes:
  dbdata:

networks:
  web-network:
